### ISSUE TITLE
Considerar cambiar los nombres de spi() y spei()

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agroclimr#38]
Actualmente estas funciones coinciden con las funciones del paquete SPEI. Esto puede generar confusiones o conflictos si se cargan los 2 paquetes al mismo tiempo. Cómo parte de la revisión de rOpenSci tendríamos que discutir la posibilidad de cambiar los nombres. 

El consenso es:
spe_*()
spei_*()

siendo * algo que resulte representativo. Tal vez tidy para hacer referencia a la filosofía de la función?

**Comment by paocorrales** [comment]
No se me ocurre ninguna opción muy convincente, por ahora tengo spi_tidy(), que no me gusta porque mezcla inglés y spi_tabla(), la versión españolizada que no se si queda muy bien.

Alguna idea @eliocamp @NatiGattinoni @yabellini ?

**Comment by yabellini** [comment]
* spi_calc()  (ya se que todas las funciones calculan, peroooo)
* spi_indice()  (ya se que la i es de indice, perooooo)
* spindice()

Me gusta mas tidy que tabla.

**Comment by paocorrales** [comment]
spi_indice() gana! Siempre me olvido de cerrar issues con commits!
